### ISSUE TITLE
Help wanted - NAV integration

### ISSUE THREAD

**Issue by pavisalavisa** [connorhu/nav-online-invoice#1]
Hi @connorhu,

I'm currently implementing a connection with NAV and I came across this repo.

I'm looking for local experts who have previous experience in building this particular connection. 

Would you be interested in providing guidance with the implementation?

**Comment by connorhu** [comment]
Hi @pavisalavisa!

This repo is in WIP status and there are a lot of missing parts. I don't recommend using it in a prod environment. It is using the 2.0 schema instead of current supported 3.0.

**Comment by pavisalavisa** [comment]
Thanks for the quick response!

That's understandable. My intent is not to use this particular implementation, but rather to find someone who knows about the potential pitfalls and quirks of the NAV system.

Do you plan on implementing the 3.0 version or have you implemented it privately sometime in the past? If so, your help would be much appreciated :)

**Comment by connorhu** [comment]
I will implement v3.0 and I will finish this implementation in the not too distant future. I don't know when.
NAV online számla system requires some implementation trick not that easy. I have experience in implementation and operation with quite a few clients. I can help you with this.

**Comment by pavisalavisa** [comment]
Amazing! 🙌 

I will reach out to you when I hit a wall. Thanks!
